name: 'Create Blog from Markdown Files'
description: 'This action allows you to create a blog from your markdown files and deploy to GitHub pages'
author: 'Kamran Ahmed <kamranahmed.se@gmail.com>'
runs:
  using: 'node16'
  main: 'src/main.js'
branding:
  icon: 'git-commit'
  color: 'orange'
inputs:
  token:
    description: >
      This option defaults to the repository scoped GitHub Token.

      However if you need more permissions for things such as deploying to another
      repository, you can add a Personal Access Token (PAT) here. This should be
      stored in the `secrets / with` menu **as a secret**.
    required: false
    default: ${{ github.token }}

  branch:
    description: 'This is the branch you wish to deploy to, for example gh-pages or docs.'
    required: false
    default: 'gh-pages'

outputs:
  deployment-status:
    description: 'The status of the deployment that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'

